-- ============================================================
-- SEKTA — FULL SCHEMA v2 (sesuai docs/konsep.md & docs/design.md)
-- Eksekusi langsung di Supabase SQL Editor: salin seluruh file → Run.
-- Aman diulang (idempotent).
--
-- Model konten block-based (design.md #32-#33):
--   articles.content = JSONB array of blocks
--   kategori, sekejap fakta, kuis (pertanyaan & opsi), sumber, terpisah.
-- ============================================================

-- ============================================================
-- 1. EKSTENSI
-- (Tabel memakai schema public — schema default Supabase)
-- ============================================================
create extension if not exists "uuid-ossp";

-- ============================================================
-- 2. TABEL
-- ============================================================

-- ---------- PROFIL USER ----------
-- Tautan 1:1 dengan auth.users. Dibuat otomatis oleh trigger.
-- role: USER | CONTRIBUTOR | ADMIN
create table if not exists public.profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  name          text not null default '',
  username      text not null default '',
  bio           text not null default '',
  avatar        text not null default '',
  role          text not null default 'USER' check (role in ('USER','CONTRIBUTOR','ADMIN')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Username unik hanya untuk nilai non-kosong (banyak user boleh kosong)
create unique index if not exists profiles_username_key
  on public.profiles (username) where username <> '';

-- ---------- KATEGORI ----------
create table if not exists public.categories (
  id           bigint generated by default as identity primary key,
  name         text not null,
  slug         text unique not null,
  description  text not null default '',
  position     integer not null default 0,
  created_at   timestamptz not null default now()
);

-- ---------- ARTIKEL ----------
-- content = JSONB array blok:
--   {"type":"paragraph","data":{"text":"..."}}
--   {"type":"heading","data":{"text":"..."}}
--   {"type":"quote","data":{"text":"..."}}
--   {"type":"list","data":{"items":["..."]}}
--   {"type":"fact","data":{"text":"..."}}
--   {"type":"divider","data":{}}
--   {"type":"quiz","data":{"quizId":"..."}}
--   {"type":"video","data":{"url":"...", "caption":"..."}}  (url YouTube atau file mp4)
-- status: DRAFT | SUBMITTED | IN_REVIEW | PUBLISHED | REJECTED | ARCHIVED
create table if not exists public.articles (
  id                bigint generated by default as identity primary key,
  author_id         uuid references public.profiles (id) on delete set null,
  author_name       text not null default 'Sekta',
  category_id       bigint references public.categories (id) on delete set null,
  title             text not null,
  slug              text unique not null,
  excerpt           text not null default '',
  cover_image       text not null default '',
  content           jsonb not null default '[]'::jsonb,
  read_time_minutes integer not null default 3,
  status            text not null default 'DRAFT' check (status in ('DRAFT','SUBMITTED','IN_REVIEW','PUBLISHED','REJECTED','ARCHIVED')),
  published_at      timestamptz,
  featured          boolean not null default false,
  view_count        integer not null default 0,
  search            tsvector generated always as (to_tsvector('indonesian', coalesce(title, '') || ' ' || coalesce(excerpt, ''))) stored,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- Migrasi untuk DB lama: tambah kolom featured & search bila belum ada
alter table public.articles add column if not exists view_count integer not null default 0;
alter table public.articles add column if not exists featured boolean not null default false;
alter table public.articles add column if not exists search tsvector
  generated always as (to_tsvector('indonesian', coalesce(title, '') || ' ' || coalesce(excerpt, ''))) stored;

-- ---------- SEKEJAP FAKTA ----------
-- Format konten khas brand (design.md #10). Wajib hook, opsional tautan artikel.
create table if not exists public.sekejap_facts (
  id          bigint generated by default as identity primary key,
  fact        text not null unique,
  article_id  bigint references public.articles (id) on delete set null,
  created_at  timestamptz not null default now()
);

-- ---------- KUIS ----------
create table if not exists public.quizzes (
  id           bigint generated by default as identity primary key,
  article_id   bigint references public.articles (id) on delete cascade,
  title        text not null unique,
  description  text not null default '',
  created_at   timestamptz not null default now()
);

create table if not exists public.quiz_questions (
  id          bigint generated by default as identity primary key,
  quiz_id     bigint not null references public.quizzes (id) on delete cascade,
  question    text not null,
  position    integer not null default 0,
  unique (quiz_id, position)
);

create table if not exists public.quiz_options (
  id          bigint generated by default as identity primary key,
  question_id bigint not null references public.quiz_questions (id) on delete cascade,
  label       text not null,
  is_correct  boolean not null default false,
  position    integer not null default 0,
  unique (question_id, position)
);

-- ---------- SUMBER (trust, design.md #30) ----------
create table if not exists public.sources (
  id          bigint generated by default as identity primary key,
  article_id  bigint not null references public.articles (id) on delete cascade,
  title       text not null,
  url         text not null default '',
  publisher   text not null default '',
  created_at  timestamptz not null default now(),
  unique (article_id, title)
);

-- ---------- ARTIKEL TERSIMPAN ----------
create table if not exists public.saved_articles (
  user_id     uuid not null references public.profiles (id) on delete cascade,
  article_id  bigint not null references public.articles (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (user_id, article_id)
);

-- ---------- REAKSI ARTIKEL ----------
-- Satu reaksi per user LOGIN per artikel (partial unique index user_id+article_id).
-- reaction: LIKE (suka) | WOW | FUNNY | SAD — ganti reaksi = UPDATE, klik lagi = hapus.
-- user_id NULL = reaksi anonim (tanpa login). Diduplikasi per session browser (session_id).
create table if not exists public.article_reactions (
  user_id    uuid references public.profiles (id) on delete cascade,
  article_id bigint not null references public.articles (id) on delete cascade,
  reaction   text not null check (reaction in ('LIKE','WOW','FUNNY','SAD')),
  session_id text,
  created_at timestamptz not null default now(),
  primary key (user_id, article_id)
);

-- Migrasi: reaksi kini boleh anonim.
-- Kolom PK tak boleh NULL, maka PK (user_id, article_id) dilepas dan diganti
-- partial unique index — dedup untuk user login (user_id) & pengunjung anonim (session_id).
alter table public.article_reactions drop constraint if exists article_reactions_pkey;
alter table public.article_reactions alter column user_id drop not null;
alter table public.article_reactions add column if not exists session_id text;
create unique index if not exists article_reactions_user_article_uniq
  on public.article_reactions (user_id, article_id) where user_id is not null;
create unique index if not exists article_reactions_session_article_uniq
  on public.article_reactions (session_id, article_id) where session_id is not null;

-- Mutasi reaksi lewat satu RPC atomik (security definer): ganti reaksi = UPDATE, klik lagi = hapus.
-- User login diidentifikasi user_id; anonim diidentifikasi session_id (localStorage browser).
-- ponytail: session_id tidak terkait IP/device — hapus localStorage berarti dapat reaksi lagi;
--           ganti ke identitas per-IP (edge function) bila perlu akurasi ketat.
create or replace function public.set_article_reaction(p_article_id bigint, p_reaction text, p_session_id text)
returns text
language plpgsql
security definer set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_existing text;
begin
  if p_reaction not in ('LIKE','WOW','FUNNY','SAD') then
    return null;
  end if;
  if v_user_id is not null then
    select reaction into v_existing from public.article_reactions
      where article_id = p_article_id and user_id = v_user_id;
    if v_existing is null then
      insert into public.article_reactions (user_id, article_id, reaction)
      values (v_user_id, p_article_id, p_reaction);
      return 'added';
    elsif v_existing = p_reaction then
      delete from public.article_reactions where article_id = p_article_id and user_id = v_user_id;
      return 'removed';
    else
      update public.article_reactions set reaction = p_reaction
        where article_id = p_article_id and user_id = v_user_id;
      return 'updated';
    end if;
  else
    if p_session_id is null or p_session_id = '' then
      return null;
    end if;
    select reaction into v_existing from public.article_reactions
      where article_id = p_article_id and session_id = p_session_id;
    if v_existing is null then
      insert into public.article_reactions (user_id, article_id, reaction, session_id)
      values (null, p_article_id, p_reaction, p_session_id);
      return 'added';
    elsif v_existing = p_reaction then
      delete from public.article_reactions where article_id = p_article_id and session_id = p_session_id;
      return 'removed';
    else
      update public.article_reactions set reaction = p_reaction
        where article_id = p_article_id and session_id = p_session_id;
      return 'updated';
    end if;
  end if;
end;
$$;
grant execute on function public.set_article_reaction(bigint, text, text) to anon, authenticated;

-- Reaksi milik pengunjung saat ini (login → user_id, anonim → session_id).
create or replace function public.my_article_reaction(p_article_id bigint, p_session_id text)
returns text
language sql
security definer set search_path = public
as $$
  select reaction from public.article_reactions
  where article_id = p_article_id
    and (user_id = auth.uid() or (user_id is null and session_id = p_session_id))
  limit 1;
$$;
grant execute on function public.my_article_reaction(bigint, text) to anon, authenticated;

-- ---------- KOMENTAR ----------
-- author_name denormalized (profiles dibatasi RLS baca-sendiri, join ke user lain tak bisa).
create table if not exists public.comments (
  id          bigint generated by default as identity primary key,
  article_id  bigint not null references public.articles (id) on delete cascade,
  user_id     uuid references public.profiles (id) on delete set null,
  author_name text not null default '',
  content     text not null check (length(content) between 1 and 1000),
  created_at  timestamptz not null default now()
);

-- ---------- NOTIFIKASI ----------
create table if not exists public.notifications (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references public.profiles (id) on delete cascade,
  title        text not null,
  description  text not null default '',
  link         text not null default '',
  unread       boolean not null default true,
  created_at   timestamptz not null default now()
);

-- Migrasi dari versi lama (kolom time adalah display text yang tidak terpakai lagi)
alter table public.notifications drop column if exists time;
alter table public.notifications add column if not exists link text not null default '';

-- ---------- VIDEO ----------
-- Video yang diunggah user (feed /video). Langsung tampil seperti Facebook,
-- tanpa moderasi (ponytail: tambah moderasi bila spam menjadi masalah).
create table if not exists public.videos (
  id           bigint generated by default as identity primary key,
  user_id      uuid references public.profiles (id) on delete set null,
  author_name  text not null default 'Pengguna',
  title        text not null default '',
  description  text not null default '',
  url          text not null,
  created_at   timestamptz not null default now()
);

-- ---------- RIWAYAT KUIS ----------
create table if not exists public.quiz_results (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references public.profiles (id) on delete cascade,
  quiz_id          bigint references public.quizzes (id) on delete set null,
  quiz_title       text not null,
  score            integer not null,
  total_questions  integer not null,
  created_at       timestamptz not null default now()
);

-- ============================================================
-- 3. FUNGSI & TRIGGER
-- ============================================================

-- Profil dibuat otomatis saat user mendaftar via Supabase Auth
-- Username diunifikasi dengan suffix bila sudah dipakai (hindari gagal insert)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  base_name     text;
  base_username text;
  username      text;
  suffix        integer := 0;
begin
  base_name := coalesce(new.raw_user_meta_data->>'full_name', '');
  -- email bisa null pada OAuth (Google); fallback '' agar NOT NULL username tak gagal
  base_username := coalesce(new.raw_user_meta_data->>'username', split_part(coalesce(new.email, ''), '@', 1));
  base_username := lower(regexp_replace(base_username, '[^a-z0-9_]', '', 'g'));
  username := base_username;
  loop
    begin
      insert into public.profiles (id, name, username, avatar)
      values (new.id, base_name, username, coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', ''))
      on conflict (id) do nothing;
      exit;
    exception when unique_violation then
      suffix := suffix + 1;
      username := base_username || suffix;
    end;
  end loop;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Update otomatis kolom updated_at (profiles & articles)
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists articles_set_updated_at on public.articles;
create trigger articles_set_updated_at
  before update on public.articles
  for each row execute function public.set_updated_at();

-- Tambah penghitung baca artikel. Dipakai dari load halaman artikel (SSR & client).
-- Security definer agar anon/authenticated boleh menaikkan tanpa policy update (RLS update hanya penulis).
-- ponytail: view_count naik setiap load (termasuk refresh & bot); dedup via cookie bila angka harus akurat.
create or replace function public.increment_article_view(aid bigint)
returns void
language sql
security definer set search_path = public
as $$
  update public.articles set view_count = view_count + 1 where id = aid;
$$;
grant execute on function public.increment_article_view(bigint) to anon, authenticated;


-- Set published_at otomatis saat artikel pertama kali di-PUBLISH
create or replace function public.articles_set_published_at()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'PUBLISHED' and new.published_at is null then
    new.published_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists articles_set_published_at on public.articles;
create trigger articles_set_published_at
  before insert or update on public.articles
  for each row execute function public.articles_set_published_at();

-- ============================================================
-- 4. ROW LEVEL SECURITY
-- ============================================================

-- PROFILES: hanya diri sendiri
alter table public.profiles enable row level security;

drop policy if exists "profil: baca sendiri" on public.profiles;
create policy "profil: baca sendiri"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "profil: ubah sendiri" on public.profiles;
create policy "profil: ubah sendiri"
  on public.profiles for update
  using (auth.uid() = id);

-- KONTEN PUBLIK: kategori, artikel (published), fakta, kuis, sumber
alter table public.categories enable row level security;
drop policy if exists "kategori: baca semua" on public.categories;
create policy "kategori: baca semua"
  on public.categories for select using (true);

alter table public.articles enable row level security;
drop policy if exists "artikel: baca published" on public.articles;
create policy "artikel: baca published"
  on public.articles for select
  using (status = 'PUBLISHED' or auth.uid() = author_id);

-- Contributor: bisa membuat & mengubah artikel miliknya sendiri
drop policy if exists "artikel: tulis penulis" on public.articles;
create policy "artikel: tulis penulis"
  on public.articles for insert
  with check (auth.uid() = author_id);

drop policy if exists "artikel: ubah penulis" on public.articles;
-- Penulis boleh mengubah kontennya, tapi tidak boleh self-publish/self-archive:
-- status PUBLISHED/IN_REVIEW/ARCHIVED hanya dari sisi admin (design.md #15, #19).
create policy "artikel: ubah penulis"
  on public.articles for update
  using (auth.uid() = author_id)
  with check (auth.uid() = author_id and status in ('DRAFT', 'SUBMITTED', 'REJECTED'));

-- Admin: lihat & kelola semua artikel (approve/reject), tulis langsung.
drop policy if exists "artikel: baca admin" on public.articles;
create policy "artikel: baca admin"
  on public.articles for select
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'ADMIN'));

drop policy if exists "artikel: kelola admin" on public.articles;
create policy "artikel: kelola admin"
  on public.articles for update
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'ADMIN'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'ADMIN'));

drop policy if exists "artikel: tulis admin" on public.articles;
create policy "artikel: tulis admin"
  on public.articles for insert
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'ADMIN'));

alter table public.sekejap_facts enable row level security;
drop policy if exists "fakta: baca semua" on public.sekejap_facts;
create policy "fakta: baca semua"
  on public.sekejap_facts for select using (true);

alter table public.quizzes enable row level security;
drop policy if exists "kuis: baca semua" on public.quizzes;
create policy "kuis: baca semua"
  on public.quizzes for select using (true);

alter table public.quiz_questions enable row level security;
drop policy if exists "soal: baca semua" on public.quiz_questions;
create policy "soal: baca semua"
  on public.quiz_questions for select using (true);

alter table public.quiz_options enable row level security;
drop policy if exists "opsi: baca semua" on public.quiz_options;
create policy "opsi: baca semua"
  on public.quiz_options for select using (true);

alter table public.sources enable row level security;
drop policy if exists "sumber: baca semua" on public.sources;
create policy "sumber: baca semua"
  on public.sources for select using (true);

-- Penulis artikel bisa menambah/mengubah sumber di artikelnya sendiri
drop policy if exists "sumber: kelola penulis" on public.sources;
create policy "sumber: kelola penulis"
  on public.sources for insert
  with check (exists (
    select 1 from public.articles a
    where a.id = article_id and a.author_id = auth.uid()
  ));

-- SAVED_ARTICLES: milik sendiri
alter table public.saved_articles enable row level security;
drop policy if exists "saved: kelola sendiri" on public.saved_articles;
create policy "saved: kelola sendiri"
  on public.saved_articles for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- NOTIFICATIONS: milik sendiri
alter table public.notifications enable row level security;
drop policy if exists "notif: baca sendiri" on public.notifications;
create policy "notif: baca sendiri"
  on public.notifications for select
  using (auth.uid() = user_id);

drop policy if exists "notif: ubah sendiri" on public.notifications;
create policy "notif: ubah sendiri"
  on public.notifications for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "notif: hapus sendiri" on public.notifications;
create policy "notif: hapus sendiri"
  on public.notifications for delete
  using (auth.uid() = user_id);

-- QUIZ_RESULTS: milik sendiri
alter table public.quiz_results enable row level security;
drop policy if exists "quiz: kelola sendiri" on public.quiz_results;
create policy "quiz: kelola sendiri"
  on public.quiz_results for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- NOTIFICATIONS: admin boleh menulis notifikasi untuk user lain (pemberitahuan
-- artikel di-approve/ditolak).
drop policy if exists "notif: tulis admin" on public.notifications;
create policy "notif: tulis admin"
  on public.notifications for insert
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'ADMIN'));

-- VIDEOS: baca publik, unggah/ubah/hapus milik sendiri
alter table public.videos enable row level security;
drop policy if exists "video: baca semua" on public.videos;
create policy "video: baca semua"
  on public.videos for select using (true);

drop policy if exists "video: unggah sendiri" on public.videos;
create policy "video: unggah sendiri"
  on public.videos for insert
  with check (auth.uid() = user_id);

drop policy if exists "video: ubah sendiri" on public.videos;
create policy "video: ubah sendiri"
  on public.videos for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "video: hapus sendiri" on public.videos;
create policy "video: hapus sendiri"
  on public.videos for delete
  using (auth.uid() = user_id);

-- ARTICLE_REACTIONS: baca siapa saja (artikel sudah publish), tulis hanya milik sendiri
alter table public.article_reactions enable row level security;
drop policy if exists "reaksi: baca" on public.article_reactions;
create policy "reaksi: baca"
  on public.article_reactions for select
  using (exists (select 1 from public.articles a where a.id = article_id and a.status = 'PUBLISHED'));

drop policy if exists "reaksi: atur sendiri" on public.article_reactions;
create policy "reaksi: atur sendiri"
  on public.article_reactions for all
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and exists (select 1 from public.articles a where a.id = article_id and a.status = 'PUBLISHED')
  );

-- Anonim boleh menambah reaksi (user_id NULL); tanpa identitas tak bisa ubah/hapus.
drop policy if exists "reaksi: tambah" on public.article_reactions;
create policy "reaksi: tambah"
  on public.article_reactions for insert
  with check (
    exists (select 1 from public.articles a where a.id = article_id and a.status = 'PUBLISHED')
    and (auth.uid() = user_id or user_id is null)
  );

-- COMMENTS: baca siapa saja (artikel publish), tulis/ubah/hapus milik sendiri
alter table public.comments enable row level security;
drop policy if exists "komentar: baca" on public.comments;
create policy "komentar: baca"
  on public.comments for select
  using (exists (select 1 from public.articles a where a.id = article_id and a.status = 'PUBLISHED'));

drop policy if exists "komentar: tulis sendiri" on public.comments;
create policy "komentar: tulis sendiri"
  on public.comments for insert
  with check (
    auth.uid() = user_id
    and exists (select 1 from public.articles a where a.id = article_id and a.status = 'PUBLISHED')
  );

drop policy if exists "komentar: ubah sendiri" on public.comments;
create policy "komentar: ubah sendiri"
  on public.comments for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "komentar: hapus sendiri" on public.comments;
create policy "komentar: hapus sendiri"
  on public.comments for delete
  using (auth.uid() = user_id);

-- ---------- STORAGE: AVATAR ----------
-- Bucket publik untuk foto profil. Path file = <user_id>/<file>.
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "avatar: baca" on storage.objects;
create policy "avatar: baca"
  on storage.objects for select
  using (bucket_id = 'avatars');

drop policy if exists "avatar: unggah sendiri" on storage.objects;
create policy "avatar: unggah sendiri"
  on storage.objects for insert
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatar: ubah sendiri" on storage.objects;
create policy "avatar: ubah sendiri"
  on storage.objects for update
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatar: hapus sendiri" on storage.objects;
create policy "avatar: hapus sendiri"
  on storage.objects for delete
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- ---------- STORAGE: VIDEO & COVER ----------
-- Bucket publik untuk video yang diunggah user dan sampul artikel (form kirim artikel).
insert into storage.buckets (id, name, public)
values ('videos', 'videos', true), ('covers', 'covers', true)
on conflict (id) do nothing;

drop policy if exists "media: baca" on storage.objects;
create policy "media: baca"
  on storage.objects for select
  using (bucket_id in ('videos', 'covers'));

drop policy if exists "media: unggah sendiri" on storage.objects;
create policy "media: unggah sendiri"
  on storage.objects for insert
  with check (bucket_id in ('videos', 'covers') and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "media: ubah sendiri" on storage.objects;
create policy "media: ubah sendiri"
  on storage.objects for update
  using (bucket_id in ('videos', 'covers') and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "media: hapus sendiri" on storage.objects;
create policy "media: hapus sendiri"
  on storage.objects for delete
  using (bucket_id in ('videos', 'covers') and (storage.foldername(name))[1] = auth.uid()::text);

-- ============================================================
-- 5. INDEX (performa kueri umum)
-- ============================================================
create index if not exists articles_status_idx        on public.articles (status);
create index if not exists articles_category_id_idx   on public.articles (category_id);
create index if not exists articles_published_at_idx  on public.articles (published_at desc);
create index if not exists articles_featured_idx      on public.articles (featured);
create index if not exists articles_search_idx        on public.articles using gin (search);
create index if not exists sekejap_facts_article_id_idx on public.sekejap_facts (article_id);
create index if not exists quizzes_article_id_idx     on public.quizzes (article_id);
create index if not exists quiz_questions_quiz_id_idx on public.quiz_questions (quiz_id);
create index if not exists quiz_options_question_id_idx on public.quiz_options (question_id);
create index if not exists sources_article_id_idx     on public.sources (article_id);
create index if not exists saved_articles_article_id_idx on public.saved_articles (article_id);
create index if not exists notifications_user_id_unread_idx on public.notifications (user_id, unread);
create index if not exists quiz_results_user_id_idx   on public.quiz_results (user_id);
create index if not exists article_reactions_article_id_idx on public.article_reactions (article_id);
create index if not exists comments_article_id_idx     on public.comments (article_id, created_at desc);
create index if not exists videos_created_at_idx       on public.videos (created_at desc);

-- ============================================================
-- 6. SEED DATA (demo)
-- ============================================================

-- ---------- KATEGORI ----------
insert into public.categories (name, slug, description, position) values
  ('Sains',      'sains',      'Fenomena alam, fisika, biologi, dan penemuan sains.', 1),
  ('Sejarah',    'sejarah',    'Peristiwa, tokoh, dan misteri masa lalu.',             2),
  ('Teknologi',  'teknologi',  'Internet, AI, dan inovasi yang mengubah cara kerja.',  3),
  ('Dunia',      'dunia',      'Fakta seputar negara, budaya, dan geografi dunia.',     4),
  ('Hewan',      'hewan',      'Fakta unik dunia satwa.',                              5),
  ('Manusia',    'manusia',    'Tubuh, pikiran, dan perilaku manusia.',                 6),
  ('Fakta Unik', 'fakta-unik', 'Fakta mengejutkan yang jarang diketahui.',              7),
  ('Kopi',       'kopi',       'Dunia kopi: sejarah, rasa, dan budaya minumnya.',        8)
on conflict (slug) do nothing;

-- ---------- ARTIKEL (block-based content) ----------
insert into public.articles (author_name, category_id, title, slug, excerpt, cover_image, content, read_time_minutes, status, published_at) values
(
  'Dr. Awan Cerah',
  (select id from public.categories where slug = 'sains'),
  'Kenapa Langit Berwarna Biru?',
  'kenapa-langit-berwarna-biru',
  'Pernahkah kamu menatap ke atas dan bertanya-tanya mengapa hamparan luas itu berwarna biru?',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Burimun_gate_and_pine_under_blue_sky_at_Beomeosa_temple_in_Busan%2C_South_Korea.jpg/1280px-Burimun_gate_and_pine_under_blue_sky_at_Beomeosa_temple_in_Busan%2C_South_Korea.jpg',
  '[
    {"type":"paragraph","data":{"text":"Pernahkah kamu menatap ke atas pada hari yang cerah dan bertanya-tanya mengapa hamparan luas itu berwarna biru? Jawabannya terletak pada interaksi menarik antara cahaya matahari dan atmosfer Bumi kita."}},
    {"type":"heading","data":{"text":"Sains di Balik Warna Biru"}},
    {"type":"paragraph","data":{"text":"Cahaya matahari, yang tampak putih bagi kita, sebenarnya terdiri dari semua warna pelangi. Ketika cahaya ini mencapai atmosfer, ia bertabrakan dengan molekul gas dan partikel lain di udara."}},
    {"type":"fact","data":{"text":"Cahaya biru lebih mudah tersebar oleh molekul udara karena memiliki panjang gelombang yang lebih pendek."}},
    {"type":"quote","data":{"text":"Semakin pendek panjang gelombang, semakin kuat cahaya tersebar — itulah alasan utama langit tampak biru."}},
    {"type":"paragraph","data":{"text":"Itulah kenapa saat matahari terbenam, langit berubah jingga dan merah. Cahaya biru sudah tersebar habis di perjalanan, menyisakan warna dengan panjang gelombang lebih panjang untuk kita lihat."}}
  ]'::jsonb,
  5,
  'PUBLISHED',
  '2023-10-12T09:00:00Z'
),
(
  'Prof. Sejarah',
  (select id from public.categories where slug = 'sejarah'),
  'Misteri Pembangunan Piramida Mesir yang Belum Terpecahkan',
  'misteri-piramida-mesir',
  'Keajaiban dunia kuno yang menyimpan ribuan rahasia arsitektur masa lalu.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Giza_Pyramids_during_%22Forever_is_Now%22_exhibition.jpg/1280px-Giza_Pyramids_during_%22Forever_is_Now%22_exhibition.jpg',
  '[
    {"type":"paragraph","data":{"text":"Piramida Agung Giza adalah satu-satunya keajaiban dunia kuno yang masih berdiri. Namun bagaimana nenek moyang membangunnya tanpa teknologi modern masih menjadi perdebatan."}},
    {"type":"heading","data":{"text":"Teori Ramping Miring"}},
    {"type":"paragraph","data":{"text":"Sejumlah ahli menduga para pekerja menarik balok batu raksasa di atas ramping pasir yang licin. Air bisa saja dipakai untuk mengurangi gesekan, sehingga memindahkan batu seberat ribuan kilogram menjadi lebih ringan."}},
    {"type":"list","data":{"items":["Batu diangkut dari tambang sejauh ratusan kilometer","Diperkirakan melibatkan puluhan ribu pekerja","Bangunan diselesaikan dalam waktu sekitar 20 tahun"]}},
    {"type":"quote","data":{"text":"Piramida bukan sekadar kuburan — ia adalah bukti kecerdasan teknik yang melampaui zamannya."}},
    {"type":"paragraph","data":{"text":"Hingga kini, tidak ada satu pun teori yang disepakati penuh. Justru itulah yang membuatnya tetap misterius dan menarik untuk diselidiki."}}
  ]'::jsonb,
  5,
  'PUBLISHED',
  '2023-11-10T09:00:00Z'
),
(
  'Tech Guru',
  (select id from public.categories where slug = 'teknologi'),
  'Bagaimana AI Akan Mengubah Cara Kita Bekerja?',
  'bagaimana-ai-mengubah-cara-kerja',
  'Kecerdasan buatan bukan lagi fiksi ilmiah, melainkan realitas harian.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Artificial_Intelligence_%28AI%29_and_Robotics_exhibition_at_the_Heinz_Nixdorf_MuseumsForum.jpg/1280px-Artificial_Intelligence_%28AI%29_and_Robotics_exhibition_at_the_Heinz_Nixdorf_MuseumsForum.jpg',
  '[
    {"type":"paragraph","data":{"text":"Kecerdasan buatan tidak lagi menjadi bahan cerita fiksi ilmiah. Dari menulis ringkasan sampai mengoreksi kode, AI sudah menjadi rekan kerja sehari-hari."}},
    {"type":"heading","data":{"text":"Bukan Menggantikan, tapi Menggeser"}},
    {"type":"paragraph","data":{"text":"Pekerjaan yang paling terdampak bukan yang paling kompleks, melainkan yang paling berulang. Yang bertahan adalah manusia yang mampu memakai AI sebagai alat bantu."}},
    {"type":"fact","data":{"text":"Sebagian besar pekerjaan masa depan belum tercipta — kombinasi manusia + AI adalah keterampilan baru yang paling dicari."}},
    {"type":"paragraph","data":{"text":"Kuncinya sederhana: pelajari cara bertanya yang baik. Kemampuan menulis prompt yang jelas akan menjadi salah satu skill paling berharga."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2023-12-01T09:00:00Z'
),
(
  'Globe Trotter',
  (select id from public.categories where slug = 'dunia'),
  'Negara Terkecil di Dunia yang Jarang Diketahui',
  'negara-terkecil-di-dunia',
  'Menjelajahi negara berdaulat dengan luas wilayah kurang dari beberapa kilometer persegi.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg/1280px-Basilica_di_San_Pietro_in_Vaticano_September_2015-1a.jpg',
  '[
    {"type":"paragraph","data":{"text":"Vatikan, dengan luas sekitar 0,44 kilometer persegi, adalah negara berdaulat terkecil di dunia. Ia dikelilingi kota Roma, Italia, dan menjadi pusat Gereja Katolik."}},
    {"type":"heading","data":{"text":"Negara dengan Penduduk Paling Sedikit"}},
    {"type":"list","data":{"items":["Populasi sekitar 800 jiwa","Tidak punya bandara maupun stasiun kereta sendiri","Mata uangnya Euro, posnya diurus Italia"]}},
    {"type":"fact","data":{"text":"Negara lain yang tak kalah kecil: Monako (2 km²) dan Nauru (21 km²)."}},
    {"type":"paragraph","data":{"text":"Meski ukurannya kecil, pengaruh budaya dan sejarahnya sangat besar bagi dunia."}}
  ]'::jsonb,
  3,
  'PUBLISHED',
  '2024-01-15T09:00:00Z'
),
(
  'Dr. Fisika',
  (select id from public.categories where slug = 'sains'),
  'Apa Itu Antimateri? Penjelasan Sederhana',
  'apa-itu-antimateri',
  'Zat misterius yang bernilai miliaran dolar per gram dan potensi energinya.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/CERN%2C_Geneva%2C_particle_accelerator_%2816284713042%29.jpg/1280px-CERN%2C_Geneva%2C_particle_accelerator_%2816284713042%29.jpg',
  '[
    {"type":"paragraph","data":{"text":"Setiap partikel di alam semesta memiliki kembaran yang disebut antipartikel. Antipartikel punya muatan berlawanan, tapi massa yang sama persis."}},
    {"type":"heading","data":{"text":"Mengapa Begitu Mahal?"}},
    {"type":"paragraph","data":{"text":"Membuat antimateri di laboratorium sangat sulit dan boros energi. Satu gram antimateri diperkirakan bernilai triliunan rupiah."}},
    {"type":"fact","data":{"text":"Ketika materi dan antimateri bertemu, keduanya saling memusnahkan dan mengubah seluruh massa menjadi energi — energi paling padat yang pernah dikenal."}},
    {"type":"quote","data":{"text":"Antimateri bukan bahan bakar pesawat masa depan — ia adalah jawaban atas pertanyaan mengapa alam semesta ada."}},
    {"type":"paragraph","data":{"text":"Ilmuwan masih meneliti mengapa alam semesta kita didominasi materi, sementara antimateri hampir tidak terlihat."}}
  ]'::jsonb,
  6,
  'PUBLISHED',
  '2024-02-20T09:00:00Z'
),
(
  'Arsiparis',
  (select id from public.categories where slug = 'sejarah'),
  'Sejarah Singkat Penemuan Internet',
  'sejarah-singkat-internet',
  'Dari ARPANET militer hingga jaringan global yang menghubungkan miliaran umat manusia.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Servers_in_a_Rack.jpg/1280px-Servers_in_a_Rack.jpg',
  '[
    {"type":"paragraph","data":{"text":"Internet lahir dari proyek ARPANET milik Departemen Pertahanan Amerika pada akhir 1960-an. Tujuannya sederhana: menghubungkan komputer antar kampus agar data tetap bisa dikirim saat sebagian jaringan rusak."}},
    {"type":"heading","data":{"text":"Dari Militer ke Publik"}},
    {"type":"paragraph","data":{"text":"Pada 1989, Tim Berners-Lee mengajukan sistem hypertext yang kelak menjadi World Wide Web. Sejak saat itu, internet berkembang dari jaringan akademik menjadi ruang publik global."}},
    {"type":"list","data":{"items":["1969 — ARPANET mengirim pesan pertama","1983 — Protokol TCP/IP diadopsi","1991 — World Wide Web dibuka untuk umum"]}},
    {"type":"quote","data":{"text":"Internet mengubah cara manusia mencari tahu — dan Sekta hadir di tengah ledakan informasi itu."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-03-05T09:00:00Z'
),
(
  'Dr. Kelautan',
  (select id from public.categories where slug = 'hewan'),
  'Gurita Punya Tiga Jantung: Fakta Satwa Paling Unik',
  'gurita-tiga-jantung',
  'Makhluk laut cerdas yang memiliki tiga jantung, darah biru, dan kemampuan menyamar luar biasa.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Octopus_vulgaris_Merculiano.jpg/1280px-Octopus_vulgaris_Merculiano.jpg',
  '[
    {"type":"paragraph","data":{"text":"Gurita bukan sekadar hewan laut biasa. Ia punya tiga jantung, sembilan otak, dan darah berwarna biru karena mengandung tembaga, bukan zat besi."}},
    {"type":"heading","data":{"text":"Kenapa Tiga Jantung?"}},
    {"type":"paragraph","data":{"text":"Dua jantung membantu memompa darah menuju insang, sementara jantung ketiga bertugas mengalirkan darah ke seluruh tubuh. Saat gurita berenang, jantung utama justru berhenti berdetak — itulah sebabnya ia lebih suka merangkak."}},
    {"type":"fact","data":{"text":"Tinta gurita ternyata juga berfungsi sebagai pengganggu indra penciuman predator, bukan sekadar tabir asap."}},
    {"type":"list","data":{"items":["Memiliki tiga jantung dan sembilan otak","Darah biru berbasis tembaga","Tidak punya kerangka sehingga bisa melewati celah sempit"]}},
    {"type":"quote","data":{"text":"Kecerdasan gurita menunjukkan bahwa otak luar biasa bisa hadir dalam bentuk yang sangat berbeda dari kita."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-04-10T09:00:00Z'
),
(
  'Dr. Kesehatan',
  (select id from public.categories where slug = 'manusia'),
  'Mengapa Tidur Sangat Penting bagi Otak?',
  'mengapa-tidur-penting',
  'Tidur bukan sekadar istirahat — ini proses pembersihan dan penguatan memori yang berlangsung di otak.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/90-year_old_Kate_Carter_in_North_Carolina_log_cabin.jpg/1280px-90-year_old_Kate_Carter_in_North_Carolina_log_cabin.jpg',
  '[
    {"type":"paragraph","data":{"text":"Saat kamu tidur, otak tidak ikut mati. Ia justru bekerja keras: membersihkan racun, mengkonsolidasikan memori, dan memperbaiki jaringan."}},
    {"type":"heading","data":{"text":"Sistem Pembuangan Otak"}},
    {"type":"paragraph","data":{"text":"Ketika tidur nyenyak, sistem glimfatik otak aktif membersihkan protein beta-amiloid yang berkaitan dengan penyakit Alzheimer. Kurang tidur berarti sampah itu menumpuk."}},
    {"type":"fact","data":{"text":"Orang dewasa disarankan tidur 7–9 jam per malam. Kurang dari 6 jam secara konsisten dikaitkan dengan penurunan daya ingat dan konsentrasi."}},
    {"type":"list","data":{"items":["Memori jangka pendek dipindahkan ke memori jangka panjang","Hormon pertumbuhan disekresikan saat tidur dalam","Emosi dan suasana hati diproses ulang saat bermimpi"]}},
    {"type":"quote","data":{"text":"Tidur yang baik adalah bentuk investasi murah untuk otak yang sehat dan tajam."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-05-18T09:00:00Z'
)
on conflict (slug) do nothing;

-- Artikel unggulan untuk hero (dikurasi)
update public.articles set featured = true
where slug in ('kenapa-langit-berwarna-biru', 'gurita-tiga-jantung');

-- ---------- SEKEJAP FAKTA ----------
insert into public.sekejap_facts (fact, article_id) values
  ('Gurita memiliki tiga jantung.', (select id from public.articles where slug = 'gurita-tiga-jantung')),
  ('Cahaya biru lebih mudah tersebar oleh molekul udara.', (select id from public.articles where slug = 'kenapa-langit-berwarna-biru')),
  ('Vatikan adalah negara berdaulat terkecil di dunia.', (select id from public.articles where slug = 'negara-terkecil-di-dunia')),
  ('Darah gurita berwarna biru karena berbasis tembaga.', (select id from public.articles where slug = 'gurita-tiga-jantung')),
  ('Kurang tidur kronis membuat protein penyebab Alzheimer menumpuk di otak.', (select id from public.articles where slug = 'mengapa-tidur-penting')),
  ('Manusia tidak dapat mencicipi makanan tanpa air liur.', null),
  ('Bumblebee dapat mengukur jarak dengan melihat kecepatan objek bergerak.', null)
on conflict (fact) do nothing;

-- ---------- KUIS: Fakta Unik Hewan ----------
insert into public.quizzes (title, description) values
  ('Fakta Unik Hewan', 'Seberapa banyak yang kamu tahu tentang dunia satwa?')
on conflict do nothing;

-- Tautkan kuis ke artikel terkait (untuk cover gambar di /quiz)
update public.quizzes set article_id = (select id from public.articles where slug = 'gurita-tiga-jantung')
where title = 'Fakta Unik Hewan' and article_id is null;

insert into public.quiz_questions (quiz_id, question, position)
select q.id, x.question, x.position
from public.quizzes q
cross join (values
  (1, 'Berapa jumlah jantung yang dimiliki gurita?', 1),
  (2, 'Hewan apa yang bisa berganti kelamin?', 2),
  (3, 'Berapa lama lumba-lumba bisa menahan napas di bawah air?', 3),
  (4, 'Hewan darat tercepat di dunia adalah?', 4),
  (5, 'Kelelawar mengenali lingkungan sekitarnya menggunakan?', 5)
) as x(no, question, position)
where q.title = 'Fakta Unik Hewan'
on conflict do nothing;

insert into public.quiz_options (question_id, label, is_correct, position)
select qq.id, x.label, x.is_correct, x.position
from public.quiz_questions qq
join public.quizzes q on q.id = qq.quiz_id
cross join (values
  (1, 'Satu', false, 1),
  (1, 'Tiga', true, 2),
  (1, 'Lima', false, 3),
  (1, 'Delapan', false, 4),
  (2, 'Ikan badut', false, 1),
  (2, 'Gurita', false, 2),
  (2, 'Ikan kakatua', true, 3),
  (2, 'Ubur-ubur', false, 4),
  (3, '5 menit', false, 1),
  (3, '15 menit', true, 2),
  (3, '1 jam', false, 3),
  (3, '3 jam', false, 4),
  (4, 'Singa', false, 1),
  (4, 'Cheetah', true, 2),
  (4, 'Kuda', false, 3),
  (4, 'Kelinci', false, 4),
  (5, 'Ekolokasi', true, 1),
  (5, 'Penglihatan tajam', false, 2),
  (5, 'Penciuman', false, 3),
  (5, 'Getaran tanah', false, 4)
) as x(qno, label, is_correct, position)
where qq.position = x.qno and q.title = 'Fakta Unik Hewan'
on conflict do nothing;

-- ---------- SUMBER ----------
insert into public.sources (article_id, title, url, publisher) values
  ((select id from public.articles where slug = 'kenapa-langit-berwarna-biru'), 'Rayleigh scattering', 'https://en.wikipedia.org/wiki/Rayleigh_scattering', 'Wikipedia'),
  ((select id from public.articles where slug = 'misteri-piramida-mesir'), 'Great Pyramid of Giza', 'https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza', 'Wikipedia'),
  ((select id from public.articles where slug = 'bagaimana-ai-mengubah-cara-kerja'), 'Future of Jobs Report', 'https://www.weforum.org/reports/the-future-of-jobs-report-2023/', 'World Economic Forum'),
  ((select id from public.articles where slug = 'apa-itu-antimateri'), 'Antimatter', 'https://en.wikipedia.org/wiki/Antimatter', 'Wikipedia'),
  ((select id from public.articles where slug = 'sejarah-singkat-internet'), 'History of the Internet', 'https://en.wikipedia.org/wiki/History_of_the_Internet', 'Wikipedia')
on conflict (article_id, title) do nothing;

-- ---------- NOTIFIKASI (untuk semua user yang sudah terdaftar) ----------
insert into public.notifications (user_id, title, description, link, unread)
select u.id, n.title, n.description, n.link, n.unread
from (values
  ('Artikel kamu telah dipublikasikan', '5 Fakta Menarik Tentang Laut', '/explore', true),
  ('Kuis baru tersedia', 'Seberapa tahu kamu tentang Antariksa?', '/quiz', true),
  ('Pembaruan Sistem v2.1', 'Fitur kuis baru dan perbaikan bug telah ditambahkan.', '', false),
  ('Pencapaian Baru: Penjelajah Fakta', 'Kamu telah membaca 50 artikel minggu ini.', '/explore', false)
) as n(title, description, link, unread)
cross join auth.users u
where not exists (
  select 1 from public.notifications n2
  where n2.user_id = u.id and n2.title = n.title
);

-- ==================== BATCH 2: ARTIKEL RISET + KUIS + FAKTA SEKEJAP ====================

-- ---------- ARTIKEL (batch 2) ----------
insert into public.articles (author_name, category_id, title, slug, excerpt, cover_image, content, read_time_minutes, status, published_at) values
(
  'Dr. Awan Cerah',
  (select id from public.categories where slug = 'sains'),
  'Cahaya Matahari Butuh 8 Menit untuk Sampai ke Bumi',
  'cahaya-matahari-8-menit',
  'Foton yang baru saja kita lihat ternyata sudah menempuh perjalanan sejak 8 menit yang lalu.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/The_sun_and_the_moon_in_South_New_Brighton%27s_beach%2C_New_Zealand.jpg/1280px-The_sun_and_the_moon_in_South_New_Brighton%27s_beach%2C_New_Zealand.jpg',
  '[
    {"type":"paragraph","data":{"text":"Ketika kamu melihat cahaya matahari, sebenarnya kamu sedang melihat masa lalu. Foton itu berangkat dari matahari sekitar 8 menit 20 detik sebelum sampai ke matamu."}},
    {"type":"heading","data":{"text":"Perjalanan 149,6 Juta Kilometer"}},
    {"type":"paragraph","data":{"text":"Jarak rata-rata Bumi ke matahari sekitar 149,6 juta kilometer. Cahaya bergerak dengan kecepatan hampir 300 ribu kilometer per detik, sehingga waktu tempuhnya sekitar 499 detik atau 8 menit 20 detik."}},
    {"type":"fact","data":{"text":"Jika matahari tiba-tiba padam, kita baru akan tahu 8 menit 20 detik kemudian."}},
    {"type":"quote","data":{"text":"Melihat cahaya matahari berarti melihat matahari yang sama persis 8 menit yang lalu."}},
    {"type":"paragraph","data":{"text":"Bandingkan dengan bintang terdekat setelah matahari, Proxima Centauri, yang cahayanya butuh lebih dari 4 tahun untuk sampai ke Bumi."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-06-05T09:00:00Z'
),
(
  'Dr. Geologi',
  (select id from public.categories where slug = 'sains'),
  'Suhu Inti Bumi Hampir Sepanas Permukaan Matahari',
  'suhu-inti-bumi',
  'Jantung planet kita bersuhu sekitar 5.200 derajat Celsius.',
  'https://commons.wikimedia.org/wiki/Special:FilePath/Stromboli_Eruption.jpg?width=1280',
  '[
    {"type":"paragraph","data":{"text":"Semakin dalam kamu masuk ke Bumi, semakin panas suhunya. Di inti dalam, perkiraan suhu mencapai 5.200 derajat Celsius."}},
    {"type":"heading","data":{"text":"Sepanas Permukaan Matahari"}},
    {"type":"paragraph","data":{"text":"Permukaan matahari sendiri bersuhu sekitar 5.500 derajat Celsius. Artinya, inti Bumi hampir sama panasnya dengan permukaan bintang yang menghidupi kita."}},
    {"type":"list","data":{"items":["Inti dalam padat, sebagian besar besi dan nikel","Tekanan di sana mencapai jutaan kali tekanan atmosfer","Inti luar yang cair berputar dan menghasilkan medan magnet Bumi"]}},
    {"type":"fact","data":{"text":"Medan magnet Bumi lahir dari gerakan besi cair di inti luar."}},
    {"type":"quote","data":{"text":"Perjalanan ke inti Bumi lebih sulit daripada ke luar angkasa."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-06-20T09:00:00Z'
),
(
  'Satelit Nusantara',
  (select id from public.categories where slug = 'teknologi'),
  'GPS dan Relativitas: Kenapa Jam Satelit Harus Dikoreksi',
  'gps-relativitas-einstein',
  'Tanpa koreksi relativitas Einstein, GPS-mu salah arah 10 kilometer setiap hari.',
  'https://commons.wikimedia.org/wiki/Special:FilePath/GPS_satellite_constellation.jpg?width=1280',
  '[
    {"type":"paragraph","data":{"text":"GPS bekerja dengan mengukur waktu tempuh sinyal dari beberapa satelit. Tapi ada satu masalah: jam di satelit berjalan berbeda dengan jam di Bumi."}},
    {"type":"heading","data":{"text":"Relativitas dalam Kehidupan Nyata"}},
    {"type":"paragraph","data":{"text":"Menurut relativitas umum, gravitasi membuat waktu berjalan lebih lambat. Karena satelit GPS berada lebih jauh dari pusat gravitasi Bumi, jam mereka berjalan sekitar 38 mikrodetik lebih cepat setiap hari dibandingkan jam di permukaan."}},
    {"type":"fact","data":{"text":"Tanpa koreksi 38 mikrodetik per hari, kesalahan posisi GPS bisa mencapai sekitar 10 kilometer per hari."}},
    {"type":"quote","data":{"text":"Setiap kali kamu membuka peta digital, kamu memakai teori relativitas Einstein."}},
    {"type":"paragraph","data":{"text":"Satelit secara rutin disinkronkan dan dikoreksi secara matematis supaya posisi yang kamu lihat tetap akurat hingga hitungan meter."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-07-02T09:00:00Z'
),
(
  'Prof. Sejarah',
  (select id from public.categories where slug = 'sejarah'),
  'Yuri Gagarin: Manusia Pertama yang Terbang ke Luar Angkasa',
  'yuri-gagarin-manusia-pertama',
  '108 menit di orbit yang mengubah sejarah umat manusia.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Yuri_Gagarin_%281961%29_-_Restoration.jpg/1280px-Yuri_Gagarin_%281961%29_-_Restoration.jpg',
  '[
    {"type":"paragraph","data":{"text":"Pada 12 April 1961, kosmonot berusia 27 tahun bernama Yuri Gagarin menjadi manusia pertama yang mengorbit Bumi."}},
    {"type":"heading","data":{"text":"Satu Orbit, 108 Menit"}},
    {"type":"paragraph","data":{"text":"Misi Vostok 1 hanya berlangsung 108 menit. Gagarin menyelesaikan satu orbit penuh mengelilingi Bumi sebelum mendarat dengan selamat."}},
    {"type":"fact","data":{"text":"Gagarin mengawali hari itu dengan kata-kata: \\"Poyekhali!\\" — \\"Ayo berangkat!\\""}},
    {"type":"quote","data":{"text":"Melihat Bumi dari orbit, Gagarin mengaku tidak melihat batas antarnegara."}},
    {"type":"paragraph","data":{"text":"Keberhasilannya menjadi titik balik perlombaan antariksa dan menginspirasi generasi penjelajah berikutnya, termasuk pendaratan manusia di Bulan delapan tahun kemudian."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-07-18T09:00:00Z'
),
(
  'Geografi Kini',
  (select id from public.categories where slug = 'dunia'),
  'Danau Retba: Danau Pink di Senegal yang Super Asin',
  'danau-pink-senegal',
  'Warna merah mudanya berasal dari alga yang tumbuh subur di air yang sangat asin.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Lac_Rose_in_Senegal.jpg/1280px-Lac_Rose_in_Senegal.jpg',
  '[
    {"type":"paragraph","data":{"text":"Di dekat ibu kota Senegal, Dakar, terdapat danau yang tampak seperti air stroberi raksasa: Danau Retba."}},
    {"type":"heading","data":{"text":"Sumber Warna Pink"}},
    {"type":"paragraph","data":{"text":"Warna merah muda itu berasal dari Dunaliella salina, sejenis alga yang menghasilkan pigmen beta-karoten sebagai pelindung diri saat air sangat asin dan sinar matahari kuat."}},
    {"type":"list","data":{"items":["Salinitas danau bisa mencapai sekitar 380 gram garam per liter","Jauh lebih asin daripada air laut biasa","Para penambang mengumpulkan garam sambil berdiri di dalam air"]}},
    {"type":"fact","data":{"text":"Warna pink danau paling kuat terlihat di musim kemarau saat salinitas naik."}},
    {"type":"quote","data":{"text":"Alam selalu punya cara untuk bertahan hidup — bahkan di air yang nyaris tak ada makhluk lain."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-08-01T09:00:00Z'
),
(
  'Bio Takjub',
  (select id from public.categories where slug = 'hewan'),
  'Tardigrade: Makhluk Paling Tangguh di Bumi',
  'tardigrade-makhluk-tangguh',
  'Bertahan di ruang hampa, radiasi mematikan, dan suhu ekstrem.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Tardigrade_under_microscope.jpg/1280px-Tardigrade_under_microscope.jpg',
  '[
    {"type":"paragraph","data":{"text":"Tardigrade, sering disebut beruang air, adalah hewan mikroskopis seukuran titik yang nyaris mustahil dibunuh."}},
    {"type":"heading","data":{"text":"Juara Bertahan Hidup"}},
    {"type":"paragraph","data":{"text":"Pada 2007, tardigrade dibawa ke orbit dan terpapar ruang hampa serta radiasi selama 10 hari. Setelah kembali ke Bumi, sebagian dari mereka hidup kembali."}},
    {"type":"list","data":{"items":["Bertahan dari -273 derajat hingga sekitar 150 derajat Celsius","Tahan terhadap radiasi ribuan kali dosis mematikan bagi manusia","Bisa hidup kembali setelah puluhan tahun dalam kondisi kering"]}},
    {"type":"fact","data":{"text":"Saat bertahan, tardigrade mengerut jadi bentuk seperti tong dan memperlambat metabolisme hingga nyaris berhenti."}},
    {"type":"quote","data":{"text":"Dari dasar laut hingga luar angkasa, tardigrade tetap tegak berdiri."}}
  ]'::jsonb,
  5,
  'PUBLISHED',
  '2024-08-15T09:00:00Z'
),
(
  'Dr. Saraf',
  (select id from public.categories where slug = 'manusia'),
  'Mengapa Jari Mengerut Saat Berendam Lama?',
  'jari-mengerut-saat-berendam',
  'Bukan karena air meresap, melainkan respons cerdas saraf tubuhmu.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Wrinkly_fingers.jpg/1280px-Wrinkly_fingers.jpg',
  '[
    {"type":"paragraph","data":{"text":"Kamu mungkin mengira jari mengerut karena menyerap air. Ternyata itu bukan alasan utamanya."}},
    {"type":"heading","data":{"text":"Tanda Tangan dari Saraf Simpatik"}},
    {"type":"paragraph","data":{"text":"Kerutan di ujung jari dikendalikan oleh sistem saraf simpatik. Buktinya, orang dengan saraf jari yang rusak tidak mengalami kerutan sama sekali meski berendam lama."}},
    {"type":"list","data":{"items":["Teori Changizi (2011): kerutan membentuk kanal drainase seperti tapak ban","Mengalirkan air keluar sehingga jari mencengkeram lebih baik","Keduanya respons evolusioner untuk kondisi basah"]}},
    {"type":"fact","data":{"text":"Jari yang mengerut terbukti membantu mencengkeram benda basah lebih mantap."}},
    {"type":"quote","data":{"text":"Tubuhmu bukan hanya bertahan, tapi juga mendesain solusi untuk lingkungannya."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-09-05T09:00:00Z'
),
(
  'Laut Dalam',
  (select id from public.categories where slug = 'fakta-unik'),
  'Emas di Dalam Laut: Ada Banyak, Tapi Tak Bisa Ditambang',
  'emas-terlarut-di-laut',
  'Lautan menyimpan emas dalam jumlah besar — tapi jangan buru-buru bawa peralatan menyelam.',
  'https://commons.wikimedia.org/wiki/Special:FilePath/GoldNuggetUSGOV.jpg?width=1280',
  '[
    {"type":"paragraph","data":{"text":"Sampai di sini, kabar menarik: laut memang mengandung emas. Kabar kurang menarik: konsentrasinya sangat, sangat encer."}},
    {"type":"heading","data":{"text":"Satu Gram per Ratus Juta Ton"}},
    {"type":"paragraph","data":{"text":"Menurut NOAA, air laut rata-rata hanya mengandung emas sekitar satu gram per 100 juta ton air. Itulah kenapa konsentrasinya diukur dalam parts per trillion."}},
    {"type":"list","data":{"items":["Estimasi klasik menyebut total emas terlarut di lautan mencapai belasan juta ton","Studi modern 2023 menghitung lebih konservatif, sekitar 14 ribu ton","Biaya ekstraksi jauh melebihi nilai emas yang didapat"]}},
    {"type":"fact","data":{"text":"Semua emas di lautan jika ditambang habis-habisan, harganya tak akan menutup biaya teknologinya."}},
    {"type":"quote","data":{"text":"Sumber daya terbesar di Bumi tak selalu yang paling berharga untuk digali."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-09-20T09:00:00Z'
),
(
  'Dr. Epidemi',
  (select id from public.categories where slug = 'fakta-unik'),
  'Nyamuk: Hewan Paling Mematikan di Dunia',
  'nyamuk-hewan-paling-mematikan',
  'Hewan yang menewaskan manusia terbanyak bukan hiu atau ular.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Mosquito_2007-2.jpg/1280px-Mosquito_2007-2.jpg',
  '[
    {"type":"paragraph","data":{"text":"Jika menyebut hewan paling mematikan, sebagian orang berpikir tentang hiu atau ular. Padahal jawabannya jauh lebih kecil: nyamuk."}},
    {"type":"heading","data":{"text":"Lebih dari 700 Ribu Kematian per Tahun"}},
    {"type":"paragraph","data":{"text":"WHO memperkirakan penyakit yang ditularkan nyamuk membunuh lebih dari 700 ribu orang setiap tahun. Malaria sendiri menyumbang ratusan ribu kematian, mayoritas anak-anak di bawah lima tahun."}},
    {"type":"list","data":{"items":["Malaria 2024: sekitar 282 juta kasus di seluruh dunia","Hanya nyamuk betina yang menggigit untuk kebutuhan protein telur","Nyamuk berkembang biak di genangan air"]}},
    {"type":"fact","data":{"text":"Bandingkan dengan hiu yang rata-rata hanya menewaskan sekitar belasan orang per tahun di seluruh dunia."}},
    {"type":"quote","data":{"text":"Yang kecil dan berisik bisa jauh lebih berbahaya daripada yang besar dan bertaring."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-10-01T09:00:00Z'
)
on conflict (slug) do nothing;

-- ---------- FAKTA SEKEJAP (batch 2) ----------
insert into public.sekejap_facts (fact, article_id) values
  ('Cahaya matahari butuh sekitar 8 menit 20 detik untuk sampai ke Bumi.', (select id from public.articles where slug = 'cahaya-matahari-8-menit')),
  ('Inti Bumi bersuhu sekitar 5.200 derajat Celsius, hampir sepanas permukaan matahari.', (select id from public.articles where slug = 'suhu-inti-bumi')),
  ('Tanpa koreksi relativitas, GPS meleset hingga 10 kilometer per hari.', (select id from public.articles where slug = 'gps-relativitas-einstein')),
  ('Yuri Gagarin menyelesaikan satu orbit Bumi hanya dalam 108 menit.', (select id from public.articles where slug = 'yuri-gagarin-manusia-pertama')),
  ('Danau Retba di Senegal tampak pink karena alga Dunaliella salina.', (select id from public.articles where slug = 'danau-pink-senegal')),
  ('Tardigrade bisa hidup kembali setelah puluhan tahun dalam keadaan kering.', (select id from public.articles where slug = 'tardigrade-makhluk-tangguh')),
  ('Jari mengerut saat berendam dikendalikan saraf, bukan karena menyerap air.', (select id from public.articles where slug = 'jari-mengerut-saat-berendam')),
  ('Konsentrasi emas di air laut sekitar satu gram per 100 juta ton air.', (select id from public.articles where slug = 'emas-terlarut-di-laut')),
  ('Nyamuk menewaskan lebih dari 700 ribu manusia setiap tahun.', (select id from public.articles where slug = 'nyamuk-hewan-paling-mematikan'))
on conflict (fact) do nothing;

-- ---------- KUIS: Antariksa & Bumi ----------
insert into public.quizzes (title, description) values
  ('Kuis Antariksa & Bumi', 'Uji pengetahuanmu tentang jarak, panas, dan orang-orang yang melampaui batas.')
on conflict do nothing;

update public.quizzes set article_id = (select id from public.articles where slug = 'cahaya-matahari-8-menit')
where title = 'Kuis Antariksa & Bumi' and article_id is null;

insert into public.quiz_questions (quiz_id, question, position)
select q.id, x.question, x.position
from public.quizzes q
cross join (values
  (1, 'Berapa lama cahaya matahari sampai ke Bumi?', 1),
  (2, 'Perkiraan suhu inti Bumi adalah?', 2),
  (3, 'Siapa manusia pertama yang mengorbit Bumi?', 3),
  (4, 'Tanpa koreksi relativitas, kesalahan GPS per hari sekitar?', 4),
  (5, 'Warna pink Danau Retba berasal dari?', 5)
) as x(no, question, position)
where q.title = 'Kuis Antariksa & Bumi'
on conflict do nothing;

insert into public.quiz_options (question_id, label, is_correct, position)
select qq.id, x.label, x.is_correct, x.position
from public.quiz_questions qq
join public.quizzes q on q.id = qq.quiz_id
cross join (values
  (1, '8 menit 20 detik', true, 1),
  (1, '8 detik', false, 2),
  (1, '8 jam', false, 3),
  (1, '80 hari', false, 4),
  (2, '5.200 derajat Celsius', true, 1),
  (2, '100 derajat Celsius', false, 2),
  (2, '1.000 derajat Celsius', false, 3),
  (2, '-50 derajat Celsius', false, 4),
  (3, 'Neil Armstrong', false, 1),
  (3, 'Yuri Gagarin', true, 2),
  (3, 'Buzz Aldrin', false, 3),
  (3, 'John Glenn', false, 4),
  (4, '10 kilometer', true, 1),
  (4, '10 sentimeter', false, 2),
  (4, '1 kilometer', false, 3),
  (4, '100 meter', false, 4),
  (5, 'Alga Dunaliella salina', true, 1),
  (5, 'Batu karang merah', false, 2),
  (5, 'Pasir mineral', false, 3),
  (5, 'Limbah industri', false, 4)
) as x(qno, label, is_correct, position)
where qq.position = x.qno and q.title = 'Kuis Antariksa & Bumi'
on conflict do nothing;

-- ---------- KUIS: Alam & Makhluk Tangguh ----------
insert into public.quizzes (title, description) values
  ('Kuis Alam & Makhluk Tangguh', 'Kenali makhluk-makhluk paling tangguh dan misteri alam.')
on conflict do nothing;

update public.quizzes set article_id = (select id from public.articles where slug = 'tardigrade-makhluk-tangguh')
where title = 'Kuis Alam & Makhluk Tangguh' and article_id is null;

insert into public.quiz_questions (quiz_id, question, position)
select q.id, x.question, x.position
from public.quizzes q
cross join (values
  (1, 'Makhluk apa yang bisa bertahan hidup di ruang hampa antariksa?', 1),
  (2, 'Mengapa jari mengerut saat berendam lama?', 2),
  (3, 'Hewan paling mematikan bagi manusia adalah?', 3),
  (4, 'Konsentrasi emas di air laut adalah?', 4),
  (5, 'Berapa lama satu orbit Yuri Gagarin berlangsung?', 5)
) as x(no, question, position)
where q.title = 'Kuis Alam & Makhluk Tangguh'
on conflict do nothing;

insert into public.quiz_options (question_id, label, is_correct, position)
select qq.id, x.label, x.is_correct, x.position
from public.quiz_questions qq
join public.quizzes q on q.id = qq.quiz_id
cross join (values
  (1, 'Tardigrade', true, 1),
  (1, 'Ubur-ubur', false, 2),
  (1, 'Kecoak', false, 3),
  (1, 'Semut', false, 4),
  (2, 'Karena menyerap air', false, 1),
  (2, 'Respons saraf untuk cengkeraman lebih baik', true, 2),
  (2, 'Karena air panas', false, 3),
  (2, 'Karena kulit terkelupas', false, 4),
  (3, 'Hiu', false, 1),
  (3, 'Ular', false, 2),
  (3, 'Nyamuk', true, 3),
  (3, 'Singa', false, 4),
  (4, 'Satu gram per 100 juta ton air', true, 1),
  (4, 'Sepadat emas batangan', false, 2),
  (4, 'Setengah dari air laut', false, 3),
  (4, 'Tidak ada sama sekali', false, 4),
  (5, '108 menit', true, 1),
  (5, '8 menit', false, 2),
  (5, '48 jam', false, 3),
  (5, '10 hari', false, 4)
) as x(qno, label, is_correct, position)
where qq.position = x.qno and q.title = 'Kuis Alam & Makhluk Tangguh'
on conflict do nothing;

-- ---------- SUMBER (batch 2) ----------
insert into public.sources (article_id, title, url, publisher) values
  ((select id from public.articles where slug = 'cahaya-matahari-8-menit'), 'Speed of light and Earth-Sun distance', 'https://en.wikipedia.org/wiki/Speed_of_light', 'Wikipedia'),
  ((select id from public.articles where slug = 'suhu-inti-bumi'), 'Earth inner core temperature', 'https://en.wikipedia.org/wiki/Earth%27s_inner_core', 'Wikipedia'),
  ((select id from public.articles where slug = 'gps-relativitas-einstein'), 'GPS and Relativity', 'https://www.nasa.gov/mission_pages/gps/', 'NASA'),
  ((select id from public.articles where slug = 'yuri-gagarin-manusia-pertama'), 'Yuri Gagarin', 'https://en.wikipedia.org/wiki/Yuri_Gagarin', 'Wikipedia'),
  ((select id from public.articles where slug = 'danau-pink-senegal'), 'Lake Retba', 'https://en.wikipedia.org/wiki/Lake_Retba', 'Wikipedia'),
  ((select id from public.articles where slug = 'tardigrade-makhluk-tangguh'), 'Tardigrades in space (FOTON-M3)', 'https://www.esa.int/ESA_Multimedia/Images/2007/09/Tardigrades_in_space', 'ESA'),
  ((select id from public.articles where slug = 'jari-mengerut-saat-berendam'), 'The evolutionary origin of fingertip wrinkling', 'https://pubmed.ncbi.nlm.nih.gov/21458250/', 'Changizi et al. (PubMed)'),
  ((select id from public.articles where slug = 'emas-terlarut-di-laut'), 'Is there gold in the ocean?', 'https://oceanservice.noaa.gov/facts/gold.html', 'NOAA Ocean Service'),
  ((select id from public.articles where slug = 'nyamuk-hewan-paling-mematikan'), 'Vector-borne diseases', 'https://www.who.int/news-room/fact-sheets/detail/vector-borne-diseases', 'World Health Organization')
on conflict (article_id, title) do nothing;

-- ==================== BATCH 3: 5 ARTIKEL + KUIS + FAKTA SEKEJAP ====================

-- ---------- ARTIKEL (batch 3) ----------
insert into public.articles (author_name, category_id, title, slug, excerpt, cover_image, content, read_time_minutes, status, published_at) values
(
  'Prof. Sejarah',
  (select id from public.categories where slug = 'sejarah'),
  'Neil Armstrong: Manusia Pertama yang Menginjakkan Kaki di Bulan',
  'neil-armstrong-manusia-pertama',
  'Satu langkah kecil bagi manusia, satu lompatan raksasa bagi umat manusia.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Pilot_Neil_Armstrong_and_X-15_-1_-_GPN-2000-000121.jpg/1280px-Pilot_Neil_Armstrong_and_X-15_-1_-_GPN-2000-000121.jpg',
  '[
    {"type":"paragraph","data":{"text":"Pada 20 Juli 1969, dunia berhenti sejenak. Neil Armstrong keluar dari modul Apollo 11 dan menjadi manusia pertama yang menginjakkan kaki di permukaan Bulan."}},
    {"type":"heading","data":{"text":"Satu Langkah Kecil"}},
    {"type":"paragraph","data":{"text":"Kalimat terkenal Armstrong — \\"Itu satu langkah kecil bagi manusia, satu lompatan raksasa bagi umat manusia\\" — didengar langsung oleh sekitar 600 juta orang di seluruh dunia."}},
    {"type":"list","data":{"items":["Misi Apollo 11 berangkat dari Kennedy Space Center","Setelah mendarat, Armstrong dan Buzz Aldrin menghabiskan sekitar 2 jam di permukaan Bulan","Mereka membawa pulang sekitar 21 kilogram batuan Bulan"]}},
    {"type":"fact","data":{"text":"Berita pendaratan di Bulan diterima langsung oleh ratusan juta orang lewat siaran televisi langsung."}},
    {"type":"quote","data":{"text":"Delapan tahun setelah Yuri Gagarin terbang ke orbit, manusia akhirnya berpijak di dunia lain."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-10-15T09:00:00Z'
),
(
  'Dr. Awan Cerah',
  (select id from public.categories where slug = 'sains'),
  'Kenapa Pelangi Selalu Melengkung?',
  'kenapa-pelangi-melengkung',
  'Bukan sekadar keindahan — lengkungannya adalah matematika cahaya.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/WhereRainbowRises.jpg/1280px-WhereRainbowRises.jpg',
  '[
    {"type":"paragraph","data":{"text":"Pelangi selalu tampak melengkung, bukan karena kebetulan. Bentuk itu adalah hasil pasti dari bagaimana cahaya dibiaskan di dalam tetesan air."}},
    {"type":"heading","data":{"text":"Sudut 42 Derajat"}},
    {"type":"paragraph","data":{"text":"Cahaya matahari yang masuk ke tetesan hujan dipantulkan di dalam dan keluar lagi. Karena pembiasan, warna keluar dengan sudut sekitar 42 derajat dari arah datang cahaya."}},
    {"type":"list","data":{"items":["Setiap tetes air bertindak seperti prisma kecil","Merah selalu di bagian luar pelangi, ungu di dalam","Itulah sebabnya kamu tidak akan pernah bisa menyentuh ujung pelangi"]}},
    {"type":"fact","data":{"text":"Pelangi terlihat melengkung karena semua titik yang memantulkan cahaya ke matamu berada pada lingkaran sudut yang sama."}},
    {"type":"quote","data":{"text":"Pelangi adalah lingkaran yang setengahnya tertutup cakrawala."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-10-25T09:00:00Z'
),
(
  'Geografi Kini',
  (select id from public.categories where slug = 'dunia'),
  'Palung Mariana: Titik Terdalam di Bumi',
  'palung-mariana-titik-terdalam',
  'Lebih dalam dari Gunung Everest jika gunung itu dibalik ke bawah.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Underwater_mcmurdo_sound.jpg/1280px-Underwater_mcmurdo_sound.jpg',
  '[
    {"type":"paragraph","data":{"text":"Di Samudra Pasifik, sekitar 200 kilometer timur Filipina, terbentang titik terdalam di Bumi: Palung Mariana."}},
    {"type":"heading","data":{"text":"Challenger Deep"}},
    {"type":"paragraph","data":{"text":"Titik terdalamnya, Challenger Deep, mencapai kedalaman sekitar 10.935 meter. Jika Gunung Everest ditaruh di sana, puncaknya masih berada lebih dari satu kilometer di bawah permukaan laut."}},
    {"type":"list","data":{"items":["Tekanan di dasar palung lebih dari 1.000 kali tekanan atmosfer di permukaan","Suhu air di kedalaman nyaris mendekati titik beku","Matahari tak pernah menembus sampai ke sini"]}},
    {"type":"fact","data":{"text":"Lebih banyak manusia yang pernah ke luar angkasa daripada yang pernah menyentuh dasar Palung Mariana."}},
    {"type":"quote","data":{"text":"Wilayah paling asing di planet kita tidak berada di langit, melainkan di bawah laut."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-11-05T09:00:00Z'
),
(
  'Dr. Saraf',
  (select id from public.categories where slug = 'manusia'),
  'Mengapa Menguap Itu Menular?',
  'kenapa-kita-menguap',
  'Lihat seseorang menguap, dan hampir pasti kamu ikut menguap.',
  'https://commons.wikimedia.org/wiki/Special:FilePath/Yawning_muscles2_%282%29.jpg?width=1280',
  '[
    {"type":"paragraph","data":{"text":"Kamu mungkin menguap saat membaca judul artikel ini. Itu bukan kebetulan — menguap dikenal sangat menular."}},
    {"type":"heading","data":{"text":"Masih Ada Misteri"}},
    {"type":"paragraph","data":{"text":"Para ilmuwan belum sepenuhnya sepakat mengapa kita menguap. Salah satu teori menyebutnya sebagai cara mendinginkan otak. Teori lain menautkan menguap yang menular dengan empati."}},
    {"type":"list","data":{"items":["Menguap lebih menular pada orang yang saling kenal","Bayi dan orang dengan beberapa kondisi tertentu jarang terpengaruh","Hewan seperti anjing juga bisa ikut menguap"]}},
    {"type":"fact","data":{"text":"Menguap yang menular dianggap berkaitan dengan kemampuan membaca perasaan orang lain."}},
    {"type":"quote","data":{"text":"Beberapa misteri tubuh manusia terletak pada hal yang paling biasa."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-11-15T09:00:00Z'
),
(
  'Laut Dalam',
  (select id from public.categories where slug = 'fakta-unik'),
  'Madu: Makanan yang (Hampir) Tidak Pernah Basi',
  'madu-tidak-pernah-basi',
  'Ditemukan di makam Mesir kuno, madu ribuan tahun masih bisa dimakan.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Three_French_monofloral_honey_jars.jpg/1280px-Three_French_monofloral_honey_jars.jpg',
  '[
    {"type":"paragraph","data":{"text":"Madu murni dikenal sebagai salah satu makanan yang hampir tidak pernah basi. Beberapa toples madu yang ditemukan di makam Mesir kuno bahkan masih aman dikonsumsi."}},
    {"type":"heading","data":{"text":"Tiga Senjata Rahasia"}},
    {"type":"paragraph","data":{"text":"Madu bertahan lama berkat kombinasi kadar air yang sangat rendah, sifat asam, dan produksi hidrogen peroksida yang dihasilkan enzim dari lebah."}},
    {"type":"list","data":{"items":["Kadar air rendah membuat bakteri sulit berkembang","Keasamannya menghambat pertumbuhan mikroorganisme","Lebah menambahkan enzim yang memproduksi agen antimikroba"]}},
    {"type":"fact","data":{"text":"Yang bisa membuat madu basi adalah kelembapan — jika tersimpan terbuka, madu menyerap air dan mulai difermentasi."}},
    {"type":"quote","data":{"text":"Racikan lebah ini lebih tahan lama daripada hampir semua makanan buatan manusia."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-11-25T09:00:00Z'
)
on conflict (slug) do nothing;

-- ---------- FAKTA SEKEJAP (batch 3) ----------
insert into public.sekejap_facts (fact, article_id) values
  ('Neil Armstrong mendarat di Bulan pada 20 Juli 1969.', (select id from public.articles where slug = 'neil-armstrong-manusia-pertama')),
  ('Pelangi selalu melengkung karena sudut pembiasan cahaya di tetes air sekitar 42 derajat.', (select id from public.articles where slug = 'kenapa-pelangi-melengkung')),
  ('Palung Mariana lebih dalam daripada tinggi Gunung Everest.', (select id from public.articles where slug = 'palung-mariana-titik-terdalam')),
  ('Menguap bisa menular dan erat kaitannya dengan empati.', (select id from public.articles where slug = 'kenapa-kita-menguap')),
  ('Madu murni hampir tidak pernah basi.', (select id from public.articles where slug = 'madu-tidak-pernah-basi'))
on conflict (fact) do nothing;

-- ---------- KUIS: Dunia & Benda Kecil ----------
insert into public.quizzes (title, description) values
  ('Kuis Dunia & Benda Kecil', 'Dari Bulan, pelangi, dasar lautan, sampai hal sehari-hari.')
on conflict do nothing;

update public.quizzes set article_id = (select id from public.articles where slug = 'neil-armstrong-manusia-pertama')
where title = 'Kuis Dunia & Benda Kecil' and article_id is null;

insert into public.quiz_questions (quiz_id, question, position)
select q.id, x.question, x.position
from public.quizzes q
cross join (values
  (1, 'Siapa manusia pertama yang menginjakkan kaki di Bulan?', 1),
  (2, 'Pelangi terbentuk karena pembiasan cahaya oleh?', 2),
  (3, 'Titik terdalam di Bumi berada di?', 3),
  (4, 'Menguap yang menular dikaitkan dengan?', 4),
  (5, 'Apa yang bisa membuat madu basi?', 5)
) as x(no, question, position)
where q.title = 'Kuis Dunia & Benda Kecil'
on conflict do nothing;

insert into public.quiz_options (question_id, label, is_correct, position)
select qq.id, x.label, x.is_correct, x.position
from public.quiz_questions qq
join public.quizzes q on q.id = qq.quiz_id
cross join (values
  (1, 'Buzz Aldrin', false, 1),
  (1, 'Neil Armstrong', true, 2),
  (1, 'Yuri Gagarin', false, 3),
  (1, 'John Glenn', false, 4),
  (2, 'Debu udara', false, 1),
  (2, 'Tetesan air hujan', true, 2),
  (2, 'Sinar bulan', false, 3),
  (2, 'Kaca jendela', false, 4),
  (3, 'Palung Mariana', true, 1),
  (3, 'Laut Mati', false, 2),
  (3, 'Danau Baikal', false, 3),
  (3, 'Gunung Everest', false, 4),
  (4, 'Empati', true, 1),
  (4, 'Kelelahan otot', false, 2),
  (4, 'Kelaparan', false, 3),
  (4, 'Suhu tubuh tinggi', false, 4),
  (5, 'Kelembapan', true, 1),
  (5, 'Sinar matahari', false, 2),
  (5, 'Suhu dingin', false, 3),
  (5, 'Getaran', false, 4)
) as x(qno, label, is_correct, position)
where qq.position = x.qno and q.title = 'Kuis Dunia & Benda Kecil'
on conflict do nothing;

-- ---------- SUMBER (batch 3) ----------
insert into public.sources (article_id, title, url, publisher) values
  ((select id from public.articles where slug = 'neil-armstrong-manusia-pertama'), 'Apollo 11', 'https://en.wikipedia.org/wiki/Apollo_11', 'Wikipedia'),
  ((select id from public.articles where slug = 'kenapa-pelangi-melengkung'), 'Rainbow', 'https://en.wikipedia.org/wiki/Rainbow', 'Wikipedia'),
  ((select id from public.articles where slug = 'palung-mariana-titik-terdalam'), 'Mariana Trench', 'https://en.wikipedia.org/wiki/Mariana_Trench', 'Wikipedia'),
  ((select id from public.articles where slug = 'kenapa-kita-menguap'), 'Yawning and contagion', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3982739/', 'NCBI (Galup et al.)'),
  ((select id from public.articles where slug = 'madu-tidak-pernah-basi'), 'Why honey never spoils', 'https://www.smithsonianmag.com/science-nature/science-of-honey-160537087/', 'Smithsonian Magazine')
on conflict (article_id, title) do nothing;

-- ==================== BATCH 4: KATEGORI KOPI + 5 ARTIKEL ====================

-- ---------- ARTIKEL (batch 4) ----------
insert into public.articles (author_name, category_id, title, slug, excerpt, cover_image, content, read_time_minutes, status, published_at) values
(
  'Penyeduh Senja',
  (select id from public.categories where slug = 'kopi'),
  'Sejarah Kopi: Dari Etiopia Hingga Secangkir Hangat Hari Ini',
  'sejarah-kopi-dari-etiopia',
  'Perjalanan biji ajaib dari pegunungan Etiopia sampai jadi ritual pagi di seluruh dunia.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_small_cup_of_coffee.JPG/1280px-A_small_cup_of_coffee.JPG',
  '[
    {"type":"paragraph","data":{"text":"Kopi punya sejarah yang legendaris. Konon dimulai di dataran tinggi Etiopia ketika seorang penggembala bernama Kaldi menyadari kambing-kambingnya menjadi lebih berenergi setelah memakan buah merah dari semak tertentu."}},
    {"type":"heading","data":{"text":"Dari Sufi ke Pasar Dunia"}},
    {"type":"paragraph","data":{"text":"Para biarawan sufi di Yaman adalah yang pertama tercatat mengolah kopi sebagai minuman pada abad ke-15, supaya tetap terjaga saat beribadah di malam hari. Dari sana kopi menyebar ke seluruh dunia Arab, lalu Eropa lewat pelabuhan Venesia."}},
    {"type":"list","data":{"items":["Etiopia adalah tempat asal-muasal kopi Arabika","Yaman menjadi gerbang penyebaran kopi ke dunia","Kedai kopi pertama di Eropa dibuka di Venesia sekitar 1645"]}},
    {"type":"fact","data":{"text":"Kata \\"coffee\\" konon berasal dari \\"qahwah\\" dalam bahasa Arab yang merujuk pada minuman ini."}},
    {"type":"quote","data":{"text":"Di belakang setiap cangkir kopi ada berabad-abad perjalanan budaya."}},
    {"type":"paragraph","data":{"text":"Hari ini kopi adalah salah satu komoditas paling diperdagangkan di dunia, dan Indonesia menjadi salah satu produsen terbesarnya."}}
  ]'::jsonb,
  5,
  'PUBLISHED',
  '2024-12-01T09:00:00Z'
),
(
  'Racik Rasa',
  (select id from public.categories where slug = 'kopi'),
  'Arabika vs Robusta: Beda Biji, Beda Karakter',
  'arabika-vs-robusta',
  'Dua spesies biji kopi paling populer dengan rasa, kafein, dan harga yang sangat berbeda.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Coffee_beans_01.jpg/1280px-Coffee_beans_01.jpg',
  '[
    {"type":"paragraph","data":{"text":"Kalau kamu membeli kopi biji, dua nama yang hampir selalu muncul adalah Arabika dan Robusta. Keduanya sangat berbeda — dari rasa sampai kandungan kafeinnya."}},
    {"type":"heading","data":{"text":"Arabika: Si Halus dan Manis"}},
    {"type":"paragraph","data":{"text":"Arabika tumbuh di dataran tinggi dan menghasilkan rasa yang lebih kompleks: asam cerah, aroma floral, dan nuansa manis. Harganya lebih mahal karena lebih sulit ditanam dan lebih rentan hama."}},
    {"type":"heading","data":{"text":"Robusta: Kuat dan Tahan Banting"}},
    {"type":"paragraph","data":{"text":"Robusta lebih mudah tumbuh di dataran rendah, lebih tahan penyakit, dan mengandung kafein hampir dua kali lipat Arabika. Rasanya cenderung pahit dan earthy — cocok untuk espresso yang pekat."}},
    {"type":"list","data":{"items":["Arabika: kafein sekitar 1,2%, rasa asam & floral","Robusta: kafein sekitar 2,2%, rasa pahit & pekat","Robusta biasanya lebih murah dan sering dipakai kopi instan"]}},
    {"type":"fact","data":{"text":"Indonesia terkenal dengan Arabika Gayo dari Aceh dan Robusta dari berbagai daerah lain."}},
    {"type":"quote","data":{"text":"Tidak ada kopi yang paling enak — hanya kopi yang paling cocok dengan seleramu."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-12-08T09:00:00Z'
),
(
  'Barista Rumah',
  (select id from public.categories where slug = 'kopi'),
  'Kenapa Kopi Bikin Melek? Ini Sains Kafein',
  'kenapa-kopi-bikin-melek',
  'Kafein bukan memberi energi — ia menutupi rasa lelahmu dari otak.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Espresso_coffee_with_brown_sugar.jpg/1280px-Espresso_coffee_with_brown_sugar.jpg',
  '[
    {"type":"paragraph","data":{"text":"Pernah merasa langsung segar setelah seteguk kopi? Kafein memang bekerja cepat, tapi cara kerjanya justru berlawanan dengan apa yang kita kira."}},
    {"type":"heading","data":{"text":"Meminjam Kantong Rasa Lelah"}},
    {"type":"paragraph","data":{"text":"Di otak ada senyawa adenosin yang menumpuk sepanjang hari dan membuat kita mengantuk. Kafein bentuknya sangat mirip adenosin, sehingga ia menempati reseptor yang sama — dan menghentikan sinyal lelah masuk."}},
    {"type":"fact","data":{"text":"Efek kafein mulai terasa sekitar 15 menit dan bertahan 4–6 jam di dalam tubuh."}},
    {"type":"list","data":{"items":["Kafein memblokir reseptor adenosin di otak","Sinyal kelelahan tertunda, bukan hilang","Saat efek habis, rasa lelah bisa datang sekaligus"]}},
    {"type":"quote","data":{"text":"Kopi tidak memberi energi — ia meminjamkan kelegaan sementara dari rasa lelah."}},
    {"type":"paragraph","data":{"text":"Itulah kenapa konsumsi kafein berlebihan di sore hari bisa mengganggu tidur malam: sisa kafein masih menempati reseptor adenosin saat kamu seharusnya tidur."}}
  ]'::jsonb,
  4,
  'PUBLISHED',
  '2024-12-15T09:00:00Z'
),
(
  'Petani Kopi Nusantara',
  (select id from public.categories where slug = 'kopi'),
  'Kopi Luwak: Sejarah dan Kontroversi di Baliknya',
  'kopi-luwak-sejarah-kontroversi',
  'Kopi termahal di dunia yang diolah lewat pencernaan musang ternyata punya sisi kelam.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Civettictis_civetta_2.jpg/1280px-Civettictis_civetta_2.jpg',
  '[
    {"type":"paragraph","data":{"text":"Kopi Luwak lahir dari kebetulan: musang luwak (palm civet) memakan buah kopi matang, dan bijinya keluar utuh setelah melewati pencernaan. Fermentasi alami ini memberi rasa yang lebih halus dan berkurang asamnya."}},
    {"type":"heading","data":{"text":"Dari Harga Selangit sampai Praktik Kelam"}},
    {"type":"paragraph","data":{"text":"Kopi Luwak bisa dijual dengan harga ratusan ribu hingga jutaan rupiah per kilogram. Popularitasnya melonjak setelah film \\"The Bucket List\\" (2007) menyebutnya."}},
    {"type":"list","data":{"items":["Luwak memilih buah kopi paling matang","Proses fermentasi alami mengurangi rasa pahit","Produksi liar memaksa luwak hidup di kandang sempit"]}},
    {"type":"fact","data":{"text":"Sebagian besar Kopi Luwak yang beredar kini berasal dari luwak yang dikurung dan diberi pakan kopi — praktik yang dikritik aktivis kesejahteraan hewan."}},
    {"type":"quote","data":{"text":"Rasa yang mewah tak seharusnya dibayar dengan penderitaan hewan."}},
    {"type":"paragraph","data":{"text":"Kini muncul alternatif etis yang meniru proses fermentasi luwak di laboratorium, tanpa melibatkan hewan sama sekali."}}
  ]'::jsonb,
  5,
  'PUBLISHED',
  '2024-12-22T09:00:00Z'
),
(
  'Kafe Data',
  (select id from public.categories where slug = 'kopi'),
  '5 Fakta Kopi yang Mungkin Belum Kamu Tahu',
  '5-fakta-kopi-belum-tahu',
  'Dari kopi sebagai buah sampai alasan cangkir kopi terlihat lebih kental di ruang gravitasi rendah.',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Latte_and_dark_coffee.jpg/1280px-Latte_and_dark_coffee.jpg',
  '[
    {"type":"paragraph","data":{"text":"Kopi punya lebih banyak cerita daripada sekadar kafein. Ini lima fakta yang mungkin belum kamu dengar."}},
    {"type":"list","data":{"items":["Kopi sebenarnya adalah biji dari buah ceri kopi","Kopi adalah buah kedua paling banyak diperdagangkan setelah minyak","Swiss Water Process dikembangkan untuk menghilangkan kafein dengan air murni"]}},
    {"type":"fact","data":{"text":"Di orbit, kopi terlihat membentuk bola di dalam cangkir karena gravitasi rendah — dan mengisinya perlu sedotan."}},
    {"type":"quote","data":{"text":"Setiap biji kopi adalah hasil ribuan jam sinar matahari dan kesabaran petani."}},
    {"type":"paragraph","data":{"text":"Menghirup aroma kopi saja sudah cukup untuk memengaruhi suasana hati — bahkan sebelum kamu meminumnya. Ilmuwan mencatat aroma kopi dapat meningkatkan kewaspadaan pada sebagian orang."}}
  ]'::jsonb,
  3,
  'PUBLISHED',
  '2024-12-29T09:00:00Z'
)
on conflict (slug) do nothing;

-- ---------- SUMBER (batch 4) ----------
insert into public.sources (article_id, title, url, publisher) values
  ((select id from public.articles where slug = 'sejarah-kopi-dari-etiopia'), 'History of coffee', 'https://en.wikipedia.org/wiki/History_of_coffee', 'Wikipedia'),
  ((select id from public.articles where slug = 'arabika-vs-robusta'), 'Coffea arabica and robusta', 'https://en.wikipedia.org/wiki/Coffea_arabica', 'Wikipedia'),
  ((select id from public.articles where slug = 'kenapa-kopi-bikin-melek'), 'Caffeine and adenosine receptors', 'https://pubmed.ncbi.nlm.nih.gov/22085335/', 'PubMed'),
  ((select id from public.articles where slug = 'kopi-luwak-sejarah-kontroversi'), 'Kopi Luwak and animal welfare', 'https://www.bbc.com/news/world-asia-37253640', 'BBC News'),
  ((select id from public.articles where slug = '5-fakta-kopi-belum-tahu'), 'Coffee facts and orbit brewing', 'https://www.smithsonianmag.com/innovation/coffee-in-space-180975510/', 'Smithsonian Magazine')
on conflict (article_id, title) do nothing;
